enum MutationTypes {
  ADD_PLAYER = 'ADD_PLAYER',
  IMPORT_PLAYERS = 'IMPORT_PLAYERS',
  UPDATE_STATS = 'UPDATE_STATS',
  EDIT_PLAYER = 'EDIT_PLAYER',
  CLEAR_EDIT_PLAYER = 'CLEAR_EDIT_PLAYER',
  DELETE_PLAYER = 'DELETE_PLAYER',
  DELETE_PLAYERS = 'DELETE_PLAYERS',
}

export default MutationTypes;
