enum MutationTypes {
  ADD_PLAYER = 'ADD_PLAYER',
  IMPORT_PLAYERS = 'IMPORT_PLAYERS',
  UPDATE_STATS = 'UPDATE_STATS',
  EDIT_PLAYER = 'EDIT_PLAYER',
  CLEAR_EDIT_PLAYER = 'CLEAR_EDIT_PLAYER',
  DELETE_PLAYER = 'DELETE_PLAYER',
  DELETE_PLAYERS = 'DELETE_PLAYERS',
  ASSIGN_CAPTAINS = 'ASSIGN_CAPTAINS',
  ASSIGN_SQUIRES = 'ASSIGN_SQUIRES',
  CLEAR_CAPTAINS = 'CLEAR_CAPTAINS',
  CLEAR_SQUIRES = 'CLEAR_SQUIRES',
  CLEAR_ALL_EXTRA = 'CLEAR_ALL_EXTRA',
  RESERVE_PLAYERS = 'RESERVE_PLAYERS',
}

export default MutationTypes;
